# Dockerfile.gps-consumer
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ex_4_consumer_gps.py .

CMD ["python","-u","ex_4_consumer_gps.py"]