# Dockerfile.agg-gps-consumer
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY agg_gps_consumer.py .

CMD ["python","-u","agg_gps_consumer.py"]