# Dockerfile.sensor-consumer
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY sensor_consumer.py .

CMD ["python","-u","sensor_consumer.py"]